" Minimal Vim Configuration

" === General ===
set nocompatible              " Use Vim defaults
set encoding=utf-8            " UTF-8 encoding
set history=1000              " Command history
set hidden                    " Allow switching buffers without saving

" === Display ===
syntax enable                 " Syntax highlighting
set number                    " Line numbers
set relativenumber            " Relative line numbers
set cursorline                " Highlight current line
set showmatch                 " Show matching brackets
set showcmd                   " Show command in bottom bar
set laststatus=2              " Always show status line
set ruler                     " Show cursor position
set scrolloff=8               " Keep 8 lines above/below cursor
set sidescrolloff=8           " Keep 8 columns left/right of cursor

" === Search ===
set incsearch                 " Search as you type
set hlsearch                  " Highlight search results
set ignorecase                " Case insensitive search
set smartcase                 " Unless uppercase used

" === Indentation ===
set autoindent                " Auto indent
set smartindent               " Smart indent
set tabstop=2                 " Tab width
set shiftwidth=2              " Indent width
set softtabstop=2             " Soft tab width
set expandtab                 " Use spaces instead of tabs

" === Editing ===
set backspace=indent,eol,start  " Backspace over everything
set clipboard=unnamed         " Use system clipboard
set mouse=a                   " Enable mouse

" === Files ===
set nobackup                  " No backup files
set nowritebackup             " No backup while editing
set noswapfile                " No swap files
set autoread                  " Auto reload changed files

" === Splits ===
set splitbelow                " Horizontal splits below
set splitright                " Vertical splits right

" === Keybindings ===
let mapleader = " "           " Space as leader key

" Clear search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Quick save
nnoremap <leader>w :w<CR>

" Quick quit
nnoremap <leader>q :q<CR>

" Better window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Move lines up/down
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Keep cursor centered when scrolling
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

" === Colors ===
set background=dark
" colorscheme desert          " Uncomment if you want a specific theme
