#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=/dev/null
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/bootstrap.sh"

log "Installing zsh customizations..."

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZSH_CUSTOM_DIR="${REPO_ROOT}/dotfiles/zsh"
ZSHRC="${HOME}/.zshrc"
OMZ_CUSTOM="${ZSH_CUSTOM:-${HOME}/.oh-my-zsh/custom}"

if [[ ! -d "${ZSH_CUSTOM_DIR}" ]]; then
  log "ERROR: Missing ${ZSH_CUSTOM_DIR}"
  return 1
fi

if [[ ! -f "${ZSHRC}" ]]; then
  log "ERROR: ${ZSHRC} not found. Install Oh My Zsh first."
  return 1
fi

# --- Primary mechanism: OMZ custom directory loader ---
# Files in $ZSH_CUSTOM/*.zsh are auto-sourced by Oh My Zsh during init.
# This survives .zshrc being regenerated by OMZ reinstall/update.
LOADER_FILE="${OMZ_CUSTOM}/dotfiles.zsh"
LOADER_CONTENT="# Auto-generated by dotfiles setup — do not edit
# Sources custom aliases, functions, path, and tool inits from the dotfiles repo.
# This file lives in \$ZSH_CUSTOM so it's auto-loaded by Oh My Zsh,
# even if ~/.zshrc is regenerated.

for file in ${ZSH_CUSTOM_DIR}/*.zsh; do
  [[ -f \"\$file\" ]] && source \"\$file\"
done"

if [[ -f "${LOADER_FILE}" ]] && grep -Fq "dotfiles/zsh" "${LOADER_FILE}"; then
  log "✓ OMZ custom loader already installed"
else
  mkdir -p "${OMZ_CUSTOM}"
  echo "${LOADER_CONTENT}" > "${LOADER_FILE}"
  log "✓ Installed OMZ custom loader: ${LOADER_FILE}"
fi

# --- Fallback: .zshrc source block ---
# Belt-and-suspenders: if the OMZ custom directory is ever blown away
# (e.g. full OMZ reinstall), this block in .zshrc still works.
SOURCE_BLOCK="# Custom aliases and functions
for file in ${ZSH_CUSTOM_DIR}/*.zsh; do
  [[ -f \"\$file\" ]] && source \"\$file\"
done"

if grep -Fq "dotfiles/zsh" "${ZSHRC}"; then
  log "✓ Zsh customizations already sourced in ${ZSHRC}"
else
  {
    echo ""
    echo "${SOURCE_BLOCK}"
  } >> "${ZSHRC}"
  log "✓ Added custom zsh sources to ${ZSHRC} (fallback)"
fi

log "✓ Zsh customizations installed"
